name:                lens-regex-pcre
version:             1.1.2.0
github:              "ChrisPenner/lens-regex-pcre"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "2019 Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A lensy interface to regular expressions
category:            Regex

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/lens-regex-pcre#readme>

dependencies:
- base >= 4.7 && < 5
- pcre-heavy
- pcre-light >= 0.4.1.0
- text
- bytestring
- lens
- template-haskell
- containers

ghc-options:
- -Wall
library:
  source-dirs: src

tests:
  lens-regex-pcre-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lens-regex-pcre
    - hspec

# benchmarks:
#   lens-regex-pcre-bench:
#     main:                Bench.hs
#     source-dirs:         bench
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - lens-regex-pcre
#     - gauge
